version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing NPM source dependencies
      - npm install
      - echo Installing the Angular CLI
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes